name: Terraform CI/CD

on:
  push:
    branches:
      - "feature/**"
      - "main"

permissions:
  contents: read

jobs:

  terraform-plan:

    if: startsWith(github.ref, 'refs/heads/feature/')

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 76ddc95a-0094-4dd0-89d2-690710c8927e
      ARM_CLIENT_SECRET: yeO8Q~MksN.~snYS5ryMFVRPn39ndCHlily1ea27
      ARM_SUBSCRIPTION_ID: ac57c821-4ca1-41cb-88d2-82700bb40c46
      ARM_TENANT_ID: 9b280cd2-7418-4667-89ff-07f51d11f345

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 76ddc95a-0094-4dd0-89d2-690710c8927e
      ARM_CLIENT_SECRET: yeO8Q~MksN.~snYS5ryMFVRPn39ndCHlily1ea27
      ARM_SUBSCRIPTION_ID: ac57c821-4ca1-41cb-88d2-82700bb40c46
      ARM_TENANT_ID: 9b280cd2-7418-4667-89ff-07f51d11f345

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve